apiVersion: v1
kind: Service
metadata:
  name: hello-world
  labels:
    app: hello-world
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: hello-world
    tier: hello-world
  type: NodePort

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello-world
  labels:
    app: hello-world
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: hello-world
        tier: hello-world
    spec:
      containers:
      - image: 127.0.0.1:30400/hello-world:$BUILD_TAG
        name: hello-world
        ports:
        - containerPort: 80
          name: hello-world
